### ISSUE TITLE
咨询一下关于费用问题

### ISSUE THREAD

**Issue by gooking** [thundernet8/YouzanPayPortal#1]
您好，看了一下，这个支付是客户直接把钱支付到了有赞的微小店里面去了

那么，想了解一下，现在从 有赞的微小店里 把钱拿出来，有赞是怎么收费的？

**Comment by thundernet8** [comment]
1%手续费


发送自我的三星盖乐世智能手机。
-------- 原始信息 --------由： gooking <notifications@github.com> 日期: 2018/2/5  07:18  (GMT+08:00) 收件人： thundernet8/YouzanPayPortal <YouzanPayPortal@noreply.github.com> 抄送： Subscribed <subscribed@noreply.github.com> 主题： [thundernet8/YouzanPayPortal] 咨询一下关于费用问题 (#1) 
您好，看了一下，这个支付是客户直接把钱支付到了有赞的微小店里面去了
那么，想了解一下，现在从 有赞的微小店里 把钱拿出来，有赞是怎么收费的？

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/thundernet8/YouzanPayPortal","title":"thundernet8/YouzanPayPortal","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/thundernet8/YouzanPayPortal"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"咨询一下关于费用问题 (#1)"}],"action":{"name":"View Issue","url":"https://github.com/thundernet8/YouzanPayPortal/issues/1"}}}
